{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-03T19:48:32.010752+00:00"}
{"level": "INFO", "message": "Shutting down", "module": "server", "line": 264, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-03T19:49:01.785975+00:00"}
{"level": "INFO", "message": "Waiting for application shutdown.", "module": "on", "line": 67, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-03T19:49:01.886844+00:00"}
{"level": "INFO", "message": "Application shutdown complete.", "module": "on", "line": 76, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-03T19:49:01.887103+00:00"}
{"level": "INFO", "message": "Finished server process [634264]", "module": "server", "line": 94, "logger": "uvicorn.error", "function": "_serve", "thread_name": "MainThread", "timestamp": "2025-09-03T19:49:01.887206+00:00"}
{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-03T19:49:05.794810+00:00"}
{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:22.434692+00:00"}
{"level": "INFO", "message": "127.0.0.1:42622 - \"POST /api/v1/movements/ HTTP/1.1\" 401", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:32.710440+00:00"}
{"level": "DEBUG", "message": "Calling on_part_begin with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917096+00:00"}
{"level": "DEBUG", "message": "Calling on_header_field with data[23:42]", "module": "multipart", "line": 625, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917428+00:00"}
{"level": "DEBUG", "message": "Calling on_header_value with data[44:70]", "module": "multipart", "line": 625, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917542+00:00"}
{"level": "DEBUG", "message": "Calling on_header_end with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917622+00:00"}
{"level": "DEBUG", "message": "Calling on_headers_finished with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917710+00:00"}
{"level": "DEBUG", "message": "Calling on_part_data with data[74:84]", "module": "multipart", "line": 625, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917828+00:00"}
{"level": "DEBUG", "message": "Calling on_part_end with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917908+00:00"}
{"level": "DEBUG", "message": "Calling on_part_begin with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.917984+00:00"}
{"level": "DEBUG", "message": "Calling on_header_field with data[109:128]", "module": "multipart", "line": 625, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918065+00:00"}
{"level": "DEBUG", "message": "Calling on_header_value with data[130:156]", "module": "multipart", "line": 625, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918143+00:00"}
{"level": "DEBUG", "message": "Calling on_header_end with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918281+00:00"}
{"level": "DEBUG", "message": "Calling on_headers_finished with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918485+00:00"}
{"level": "DEBUG", "message": "Calling on_part_data with data[160:170]", "module": "multipart", "line": 625, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918672+00:00"}
{"level": "DEBUG", "message": "Calling on_part_end with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918808+00:00"}
{"level": "DEBUG", "message": "Calling on_end with no data", "module": "multipart", "line": 628, "logger": "python_multipart.multipart", "function": "callback", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.918937+00:00"}
{"level": "INFO", "message": "Root endpoint accessed by 127.0.0.1", "module": "user_auth", "line": 117, "logger": "general_logger", "function": "user_login_v1", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.927738+00:00"}
{"level": "WARNING", "message": "(trapped) error reading bcrypt version", "module": "bcrypt", "line": 622, "logger": "passlib.handlers.bcrypt", "function": "_load_backend_mixin", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.951040+00:00", "exc_info": "Traceback (most recent call last):\n  File \"/home/devenzo35/dev/backend/OrderFlow/.venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py\", line 620, in _load_backend_mixin\n    version = _bcrypt.__about__.__version__\n              ^^^^^^^^^^^^^^^^^\nAttributeError: module 'bcrypt' has no attribute '__about__'"}
{"level": "DEBUG", "message": "detected 'bcrypt' backend, version '<unknown>'", "module": "bcrypt", "line": 625, "logger": "passlib.handlers.bcrypt", "function": "_load_backend_mixin", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.952725+00:00"}
{"level": "DEBUG", "message": "'bcrypt' backend lacks $2$ support, enabling workaround", "module": "bcrypt", "line": 406, "logger": "passlib.handlers.bcrypt", "function": "_finalize_backend_mixin", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:36.952892+00:00"}
{"level": "INFO", "message": "127.0.0.1:42622 - \"POST /api/v1/auth/login HTTP/1.1\" 200", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:37.227118+00:00"}
{"level": "INFO", "message": "127.0.0.1:47256 - \"POST /api/v1/movements/ HTTP/1.1\" 400", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:50:44.687206+00:00"}
{"level": "INFO", "message": "127.0.0.1:35184 - \"GET /api/v1/categories HTTP/1.1\" 307", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:51:13.909894+00:00"}
{"level": "INFO", "message": "127.0.0.1:35184 - \"GET /api/v1/categories/ HTTP/1.1\" 401", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:51:13.914336+00:00"}
{"level": "INFO", "message": "127.0.0.1:55158 - \"GET /api/v1/categories HTTP/1.1\" 307", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:51:19.919259+00:00"}
{"level": "INFO", "message": "127.0.0.1:55158 - \"GET /api/v1/categories/ HTTP/1.1\" 200", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:51:19.928617+00:00"}
{"level": "INFO", "message": "127.0.0.1:43974 - \"POST /api/v1/movements/ HTTP/1.1\" 422", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:51:59.191673+00:00"}
{"level": "INFO", "message": "User 5 created movement: 68", "module": "movements", "line": 130, "logger": "general_logger", "function": "create_movement_v1", "thread_name": "MainThread", "timestamp": "2025-09-04T17:52:21.850482+00:00"}
{"level": "INFO", "message": "127.0.0.1:51524 - \"POST /api/v1/movements/ HTTP/1.1\" 201", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-04T17:52:21.855456+00:00"}
{"level": "INFO", "message": "Shutting down", "module": "server", "line": 264, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-04T17:55:50.370057+00:00"}
{"level": "INFO", "message": "Waiting for application shutdown.", "module": "on", "line": 67, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-04T17:55:50.470862+00:00"}
{"level": "INFO", "message": "Application shutdown complete.", "module": "on", "line": 76, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-04T17:55:50.471181+00:00"}
{"level": "INFO", "message": "Finished server process [815574]", "module": "server", "line": 94, "logger": "uvicorn.error", "function": "_serve", "thread_name": "MainThread", "timestamp": "2025-09-04T17:55:50.471302+00:00"}
{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-04T17:59:07.446586+00:00"}
{"level": "INFO", "message": "Shutting down", "module": "server", "line": 264, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-05T18:06:24.792542+00:00"}
{"level": "INFO", "message": "Waiting for application shutdown.", "module": "on", "line": 67, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-05T18:06:24.892931+00:00"}
{"level": "INFO", "message": "Application shutdown complete.", "module": "on", "line": 76, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-05T18:06:24.893213+00:00"}
{"level": "INFO", "message": "Finished server process [820368]", "module": "server", "line": 94, "logger": "uvicorn.error", "function": "_serve", "thread_name": "MainThread", "timestamp": "2025-09-05T18:06:24.893327+00:00"}
{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-12T13:00:37.671554+00:00"}
{"level": "INFO", "message": "Shutting down", "module": "server", "line": 264, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-12T13:00:40.286995+00:00"}
{"level": "INFO", "message": "Waiting for application shutdown.", "module": "on", "line": 67, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-12T13:00:40.387556+00:00"}
{"level": "INFO", "message": "Application shutdown complete.", "module": "on", "line": 76, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-12T13:00:40.388337+00:00"}
{"level": "INFO", "message": "Finished server process [263081]", "module": "server", "line": 94, "logger": "uvicorn.error", "function": "_serve", "thread_name": "MainThread", "timestamp": "2025-09-12T13:00:40.388773+00:00"}
{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-12T13:11:50.351227+00:00"}
{"level": "INFO", "message": "Application startup complete.", "module": "on", "line": 62, "logger": "uvicorn.error", "function": "startup", "thread_name": "MainThread", "timestamp": "2025-09-15T11:58:32.878801+00:00"}
{"level": "INFO", "message": "127.0.0.1:41810 - \"GET /api/v1/categories/ HTTP/1.1\" 401", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-15T11:58:48.837929+00:00"}
{"level": "INFO", "message": "127.0.0.1:41814 - \"GET /api/v1/categories/ HTTP/1.1\" 500", "module": "httptools_impl", "line": 476, "logger": "uvicorn.access", "function": "send", "thread_name": "MainThread", "timestamp": "2025-09-15T11:58:54.086642+00:00"}
{"level": "ERROR", "message": "Exception in ASGI application\n", "module": "httptools_impl", "line": 414, "logger": "uvicorn.error", "function": "run_asgi", "thread_name": "MainThread", "timestamp": "2025-09-15T11:58:54.086848+00:00", "exc_info": "Traceback (most recent call last):\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 409, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n    return await self.app(scope, receive, send)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/fastapi/applications.py\", line 1054, in __call__\n    await super().__call__(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/applications.py\", line 113, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py\", line 186, in __call__\n    raise exc\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 85, in __call__\n    await self.app(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 75, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/fastapi/routing.py\", line 292, in app\n    solved_result = await solve_dependencies(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py\", line 615, in solve_dependencies\n    solved_result = await solve_dependencies(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py\", line 634, in solve_dependencies\n    solved = await solve_generator(\n             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py\", line 560, in solve_generator\n    return await stack.enter_async_context(cm)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/contextlib.py\", line 659, in enter_async_context\n    result = await _enter(cm)\n             ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/app/dependencies.py\", line 26, in get_db\n    async with asyncEngine.begin() as conn:\n  File \"/usr/lib/python3.12/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3277, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 143, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3301, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 447, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 711, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    with util.safe_reraise():\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 175, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 388, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 673, in __init__\n    self.__connect()\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 899, in __connect\n    with util.safe_reraise():\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 895, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 661, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 629, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 964, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/home/devenzo35/dev/backend/order_flow/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"uvloop/loop.pyx\", line 2043, in create_connection\n  File \"uvloop/loop.pyx\", line 2020, in uvloop.loop.Loop.create_connection\nConnectionRefusedError: [Errno 111] Connection refused"}
{"level": "INFO", "message": "Shutting down", "module": "server", "line": 264, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-15T11:59:43.733787+00:00"}
{"level": "INFO", "message": "Waiting for application shutdown.", "module": "on", "line": 67, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-15T11:59:43.834262+00:00"}
{"level": "INFO", "message": "Application shutdown complete.", "module": "on", "line": 76, "logger": "uvicorn.error", "function": "shutdown", "thread_name": "MainThread", "timestamp": "2025-09-15T11:59:43.834479+00:00"}
{"level": "INFO", "message": "Finished server process [40485]", "module": "server", "line": 94, "logger": "uvicorn.error", "function": "_serve", "thread_name": "MainThread", "timestamp": "2025-09-15T11:59:43.834587+00:00"}
